// Crop choices for plots. Edit to change the list.
export const CROPS = ["Groundnut", "Sesamum", "Sunflower", "Paddy", "Rice", "Urad"];

export const PREVIOUS_CROPS = [
  "NA",
  "Paddy",
  "Wheat",
  "Maize",
  "Bajra (Pearl millet)",
  "Jowar (Sorghum)",
  "Ragi",
  "Groundnut",
  "Soybean",
  "Mustard",
  "Sesamum",
  "Cotton",
  "Sugarcane",
  "Gram (Chickpea)",
  "Arhar/Tur",
  "Moong",
  "Urad",
  "Masoor",
  "Pea",
  "Potato",
  "Onion",
  "Tomato",
  "Chilli",
  "Coriander",
  "Cumin",
  "Fennel",
  "Vegetables/Mixed",
  "Fodder",
  "Fallow",
];
